!###########################################################
!# SUBROUTINE: MCTDH_readInputCRP3D
!###########################################################
!> @brief
!! Wrapper subroutine to read a typical CRP3D input file.
!
!> @warning
!! - It will need the static library generated by OOPtrajtou.
!
!> @author A.S. Muzas - alberto.muzas@uam.es
!> @date Oct/2014
!> @version 1.0
!-----------------------------------------------------------
SUBROUTINE MCTDH_readInputCRP3D(crp3d_pes)
   ! Initial declarations
   USE CRP3D_MOD
   IMPLICIT NONE
   ! I/O variables
   TYPE(CRP3D),INTENT(OUT) :: crp3d_pes
   ! Run section
   CALL crp3d_pes%INITIALIZE("INcrp3d.inp")
   RETURN
END SUBROUTINE MCTDH_readInputCRP3D
!###########################################################
!# SUBROUTINE: MCTDH_readInputCRP6D
!###########################################################
!> @brief
!! Wrapper subroutine to read a typical CRP6D input file.
!
!> @warning
!! - It will need the static library generated by OOPtrajtou.
!
!> @author A.S. Muzas - alberto.muzas@uam.es
!> @date Oct/2014
!> @version 1.0
!-----------------------------------------------------------
SUBROUTINE MCTDH_readInputCRP6D(crp6d_pes)
   ! Initial declarations
   USE CRP6D_MOD
   IMPLICIT NONE
   ! I/O variables
   TYPE(CRP6D),INTENT(OUT) :: crp6d_pes
   ! Run section
   ! Change coordinates
   CALL crp6d_pes%INITIALIZE("INcrp6d.inp")
   RETURN
END SUBROUTINE MCTDH_readInputCRP6D
!###########################################################
!# SUBROUTINE: MCTDH_GetPotCRP3D
!###########################################################
!> @brief
!! Wrapper subroutine to get the CRP3D potential at a given point
!! r in space
!
!> @warning
!! - It will need the static library generated by OOPtrajtou.
!! - It is assumed that the potential is evaluated at a point 'r', which
!!   is given in a.u. normalized surface coordinates, i.e. in atomic units
!!   along the direction of surface vectors (standard way of MCTDH)
!
!> @author A.S. Muzas - alberto.muzas@uam.es
!> @date Oct/2014
!> @version 1.0
!-----------------------------------------------------------
SUBROUTINE MCTDH_getPotCRP3D(crp3d_pes,r,v)
   ! Initial declarations
   USE CRP3D_MOD
   USE UNITS_MOD
   IMPLICIT NONE
   ! I/O variables
   TYPE(CRP3D),INTENT(IN) :: crp3d_pes
   REAL(KIND=8),DIMENSION(3),INTENT(IN) :: r
   REAL(KIND=8),INTENT(OUT) :: v
   ! Run section
   ! Change of coordinates:
   r(1:2) = crp3d_pes%surf%surfunit2cart(r(1:2))
   v = crp3d_pes%getpot(r)
   RETURN
END SUBROUTINE MCTDH_getPotCRP3D
!###########################################################
!# SUBROUTINE: MCTDH_GetPotCRP6D
!###########################################################
!> @brief
!! Wrapper subroutine to get the CRP6D potential at a given point
!! r in space
!
!> @warning
!! - It will need the static library generated by OOPtrajtou.
!! - It is assumed that the potential is evaluated at a point 'r', which
!!   is given in a.u. normalized surface coordinates, i.e. in atomic units
!!   along the direction of surface vectors (standard way of MCTDH)
!
!> @author A.S. Muzas - alberto.muzas@uam.es
!> @date Oct/2014
!> @version 1.0
!-----------------------------------------------------------
SUBROUTINE MCTDH_getPotCRP6D(crp6d_pes,r,v)
   ! Initial declarations
   USE CRP6D_MOD
   USE UNITS_MOD
   IMPLICIT NONE
   ! I/O variables
   TYPE(CRP6D),INTENT(IN) :: crp6d_pes
   REAL(KIND=8),DIMENSION(6),INTENT(IN) :: r
   REAL(KIND=8),INTENT(OUT) :: v
   ! Run section
   ! Change of coordinates:
   r(1:2) = crp6d_pes%surf%surfunit2cart(r(1:2))
   v = crp6d_pes%getpot(r)
   RETURN
END SUBROUTINE MCTDH_getPotCRP6D
