PROGRAM ANALYSIS
USE DEBUG_MOD
USE DIFFRACTIONCRP3D_MOD
TYPE(Allowed_peaksCRP3D) :: this
CALL SET_VERBOSE_MODE(.TRUE.)
CALL this%INITIALIZE("INsurface.inp","INinicond3d.inp")
CALL this%SETUP()
CALL this%ASSIGN_PEAKS()
CALL this%PRINT_LABMOMENTA_AND_ANGLES()
END PROGRAM ANALYSIS
