PROGRAM TEST_CRP6D
! Initial declarations
USE CRP6D_MOD
USE DEBUG_MOD
IMPLICIT NONE
! Variables
TYPE(CRP6D) :: thispes
REAL(KIND=8) :: dist
CALL SET_VERBOSE_MODE(.FALSE.)
CALL SET_DEBUG_MODE(.FALSE.)
WRITE(*,*) "CHEAT CUT2D"
WRITE(*,*) "Type a distance (au, real*8)"
READ(*,*) dist
! STEP 1: READ CRP6D INPUT FILES
CALL thispes%READ("INcrp6d.inp")
! STEP 2: EXTRACT VACUUM POTENTIAL & CHEAT
CALL thispes%EXTRACT_VACUUMSURF()
CALL thispes%CHEAT_CARTWHEEL_ONTOP(1,1,2,dist)
CALL thispes%CHEAT_CARTWHEEL_ONTOP(2,1,1,dist)
! STEP 3: ADD VACUUM POTENTIAL & PRINT
CALL thispes%ADD_VACUUMSURF()
CALL thispes%wyckoffsite(1)%zrcut(1)%PRINT_INPUT("Li-input.inp")
CALL thispes%wyckoffsite(2)%zrcut(1)%PRINT_INPUT("F-input.inp")
! STEP 4: GOODBYE! 
CALL EXIT(0)
END PROGRAM TEST_CRP6D
