!#########################################################
! MODULE: LINK_FUNCTION1D_MOD
!> @brief
!! Link for all routines regarding 1D functions 
!##########################################################
MODULE LINK_FUNCTION1D_MOD
   USE FUNCTION1D_MOD
   USE ONE_FUNCTION_MOD
   USE ZERO_FUNCTION_MOD
   USE LOGISTIC_FUNCTION_MOD
   USE LINEAR_FUNCTION_MOD
   USE EXPONENTIAL_FUNCTION_MOD
   USE XEXPONENTIAL_FUNCTION_MOD
   USE XPLUSNEXPONENTIAL_FUNCTION_MOD
END MODULE LINK_FUNCTION1D_MOD 
