#!/bin/bash
if [ $OOPTRAJTOUPATH ];then
	echo OOPTRAJTOUPATH is an environmental variable
else
	echo OOPTRAJTOUPATH isn\'t an environmental variable
	exit 1
fi
# Erase previous documentation
rm -r $OOPTRAJTOUPATH/doc/latex
if [ "$?" == 0 ];then echo LaTeX old documentation was erased;fi
rm -r $OOPTRAJTOUPATH/doc/html
if [ "$?" == 0 ];then echo HTML old documentation was erased;fi
rm -r $OOPTRAJTOUPATH/doc/man
if [ "$?" == 0 ];then echo Manual old documentation was erased;fi
# If this was executed in OOPTRAJTOUPATH, generate documentation
if [ "$PWD" != $OOPTRAJTOUPATH ];then
	echo This script should be executed in $OOPTRAJTOUPATH
	echo It was executed here: $PWD
	exit 1
fi
conf=$OOPTRAJTOUPATH/doc/doxygenconf/all.conf
echo Cobnfiguration file in $conf
doxygen $conf
cd $OOPTRAJTOUPATH/doc/latex
make pdf
mv refman.pdf ../.
echo LaTeX documentation created inside $OOPTRAJTOUPATH/doc/latex
echo MANual documentation created inside $OOPTRAJTOUPATH/doc/man
echo HTML documentation created inside $OOPTRAJTOUPATH/doc/html
echo PDF documentation generated in $OOPTRAJTOUPATH/doc/refman.pdf
echo log file generated inside $OOPTRAJTOUPATH/doc/logs/error.log
echo 
#
